import { CarLink, InitialDriver } from '../types';
import { CARS } from './teams';
import { DRIVER_TRAITS } from './traits';

type DriverSeed = Omit<InitialDriver, 'carLink'>;

const DRIVER_CAR_LINKS: Record<number, CarLink> = {
  1: { compatibility: 94, adaptation: 90, notes: 'Lives in perfect sync with a sharp front end.' },
  3: { compatibility: 77, adaptation: 63, notes: 'Prefers planted rear stability, slower to adjust.' },
  4: { compatibility: 86, adaptation: 82, notes: 'Thrives with pointy balance and quick reactions.' },
  5: { compatibility: 84, adaptation: 78, notes: 'Front-limited setups suit his rotation style.' },
  6: { compatibility: 70, adaptation: 60, notes: 'Sensitive to ride height shifts and gusty aero.' },
  7: { compatibility: 88, adaptation: 82, notes: 'Confident with agile rear rotation and fast tweaks.' },
  8: { compatibility: 82, adaptation: 87, notes: 'Adapts rapidly once balance is in the window.' },
  9: { compatibility: 76, adaptation: 69, notes: 'Needs laps to trust front grip and brake feel.' },
  10:{ compatibility: 72, adaptation: 65, notes: 'Prefers stable baseline, slower to pivot setups.' },
  11:{ compatibility: 79, adaptation: 68, notes: 'Better once he feels rear stability in traction zones.' },
  12:{ compatibility: 58, adaptation: 55, notes: 'Strained link—requires coaching to unlock confidence.' },
  13:{ compatibility: 73, adaptation: 74, notes: 'Explosive when comfortable but volatile early.' },
  18:{ compatibility: 67, adaptation: 70, notes: 'Methodical acclimation to brake and tyre behaviour.' },
  19:{ compatibility: 69, adaptation: 62, notes: 'Needs predictable rear; struggles with peaky aero.' },
  21:{ compatibility: 75, adaptation: 72, notes: 'Solid baseline feel, improves steadily through weekend.' },
  22:{ compatibility: 83, adaptation: 76, notes: 'Quickly settles when steering weight is consistent.' },
  23:{ compatibility: 78, adaptation: 85, notes: 'Fast learner, still refining feedback language.' },
  24:{ compatibility: 81, adaptation: 80, notes: 'Smooth driver who gels with compliant chassis.' },
  25:{ compatibility: 65, adaptation: 58, notes: 'Weak link—needs time to trust new aero balance.' },
  27:{ compatibility: 62, adaptation: 60, notes: 'Car feel mismatch; big swings session to session.' },
  28:{ compatibility: 71, adaptation: 67, notes: 'Improves as stints go long and balance stabilises.' },
  29:{ compatibility: 86, adaptation: 88, notes: 'Excellent synergy—feels changes instantly.' },
  30:{ compatibility: 74, adaptation: 66, notes: 'Prefers understeer; wary of sharp front-end car.' },
  31:{ compatibility: 69, adaptation: 64, notes: 'Needs confidence runs before pushing limits.' },
  32:{ compatibility: 90, adaptation: 92, notes: 'Feels at one with the chassis immediately.' },
};

// The roster is now set to the definitive 2025 season lineup with refreshed specialties.
const DRIVER_SEED: DriverSeed[] = [
  // McLaren Formula 1 Team
  {
    id: 8,
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    driverSkills: {
      overall: 95,
      qualifyingPace: 97,
      raceCraft: 94,
      tyreManagement: 93,
      consistency: 97,
      wetWeatherSkill: 90,
      aggressionIndex: 74,
      incidentProneness: 96,
      loyalty: 99,
      potential: 99,
      reputation: 90,
      specialties: ['Apex Precision', 'Error-Free Runs'],
      trait: DRIVER_TRAITS.MR_CONSISTENT,
    },
    car: CARS.McLaren,
    rookie: false,
    age: 24,
    contractExpiresIn: 3,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 6000000,
    form: 0,
    happiness: 85,
    morale: 90,
    careerHistory: { 2025: 'McLaren Formula 1 Team' },
  },
  {
    id: 7,
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 4,
    driverSkills: {
      overall: 96,
      qualifyingPace: 97,
      raceCraft: 93,
      tyreManagement: 95,
      consistency: 93,
      wetWeatherSkill: 97,
      aggressionIndex: 82,
      incidentProneness: 92,
      loyalty: 100,
      potential: 98,
      reputation: 94,
      specialties: ['Wet Weather Control', 'Qualifying Attacks'],
      trait: DRIVER_TRAITS.RAIN_MASTER,
    },
    car: CARS.McLaren,
    rookie: false,
    age: 25,
    contractExpiresIn: 4,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 30000000,
    form: 0,
    happiness: 90,
    morale: 88,
    careerHistory: { 2025: 'McLaren Formula 1 Team' },
  },

  // Oracle Red Bull Racing
  {
    id: 1,
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 1,
    driverSkills: {
      overall: 97,
      qualifyingPace: 99,
      raceCraft: 99,
      tyreManagement: 88,
      consistency: 95,
      wetWeatherSkill: 99,
      aggressionIndex: 96,
      incidentProneness: 90,
      loyalty: 95,
      potential: 97,
      reputation: 99,
      specialties: ['Late Braker', 'Race Pace Bully', 'Adaptable Lines'],
      trait: DRIVER_TRAITS.THE_OVERTAKER,
    },
    car: CARS.RedBull,
    rookie: false,
    age: 27,
    contractExpiresIn: 4,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 55000000,
    form: 0,
    happiness: 95,
    morale: 95,
    careerHistory: { 2025: 'Oracle Red Bull Racing' },
  },
  {
    id: 13,
    name: 'Yuki Tsunoda',
    shortName: 'TSU',
    number: 22,
    driverSkills: {
      overall: 78,
      qualifyingPace: 82,
      raceCraft: 81,
      tyreManagement: 74,
      consistency: 76,
      wetWeatherSkill: 80,
      aggressionIndex: 87,
      incidentProneness: 78,
      loyalty: 95,
      potential: 90,
      reputation: 80,
      specialties: ['Send It', 'Counter Moves'],
      trait: DRIVER_TRAITS.ERROR_PRONE,
    },
    car: CARS.RedBull,
    rookie: false,
    age: 25,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 2500000,
    form: 0,
    happiness: 70,
    morale: 75,
    careerHistory: { 2025: 'Oracle Red Bull Racing' },
  },

  // Mercedes-AMG Petronas Formula One Team
  {
    id: 4,
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    driverSkills: {
      overall: 93,
      qualifyingPace: 95,
      raceCraft: 90,
      tyreManagement: 89,
      consistency: 95,
      wetWeatherSkill: 92,
      aggressionIndex: 80,
      incidentProneness: 86,
      loyalty: 98,
      potential: 95,
      reputation: 92,
      specialties: ['Qualifying Maestro', 'Race Restarts'],
      trait: DRIVER_TRAITS.MR_SATURDAY,
    },
    car: CARS.Mercedes,
    rookie: false,
    age: 27,
    contractExpiresIn: 2,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 18000000,
    form: 0,
    happiness: 80,
    morale: 82,
    careerHistory: { 2025: 'Mercedes-AMG Petronas Formula One Team' },
  },
  {
    id: 23,
    name: 'Andrea Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    driverSkills: {
      overall: 82,
      qualifyingPace: 85,
      raceCraft: 82,
      tyreManagement: 80,
      consistency: 84,
      wetWeatherSkill: 83,
      aggressionIndex: 86,
      incidentProneness: 80,
      loyalty: 98,
      potential: 99,
      reputation: 72,
      specialties: ['Rising Star', 'Late-race Composure'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.Mercedes,
    rookie: true,
    age: 19,
    contractExpiresIn: 3,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 1000000,
    form: 0,
    happiness: 85,
    morale: 85,
    careerHistory: { 2025: 'Mercedes-AMG Petronas Formula One Team' },
  },

  // Scuderia Ferrari
  {
    id: 5,
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    driverSkills: {
      overall: 92,
      qualifyingPace: 99,
      raceCraft: 93,
      tyreManagement: 88,
      consistency: 86,
      wetWeatherSkill: 86,
      aggressionIndex: 85,
      incidentProneness: 83,
      loyalty: 100,
      potential: 96,
      reputation: 94,
      specialties: ['Quali Artist', 'Turn-in Specialist'],
      trait: DRIVER_TRAITS.MR_SATURDAY,
    },
    car: CARS.Ferrari,
    rookie: false,
    age: 27,
    contractExpiresIn: 5,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 35000000,
    form: 0,
    happiness: 88,
    morale: 85,
    careerHistory: { 2025: 'Scuderia Ferrari' },
  },
  {
    id: 3,
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    driverSkills: {
      overall: 93,
      qualifyingPace: 90,
      raceCraft: 98,
      tyreManagement: 98,
      consistency: 92,
      wetWeatherSkill: 98,
      aggressionIndex: 72,
      incidentProneness: 94,
      loyalty: 90,
      potential: 72,
      reputation: 98,
      specialties: ['Tyre Life Guru', 'Wet-Weather Rhythm', 'Racecraft IQ'],
      trait: DRIVER_TRAITS.TYRE_WHISPERER,
    },
    car: CARS.Ferrari,
    rookie: false,
    age: 40,
    contractExpiresIn: 2,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 55000000,
    form: 0,
    happiness: 92,
    morale: 90,
    careerHistory: { 2025: 'Scuderia Ferrari' },
  },

  // Williams Racing
  {
    id: 19,
    name: 'Alexander Albon',
    shortName: 'ALB',
    number: 23,
    driverSkills: {
      overall: 90,
      qualifyingPace: 91,
      raceCraft: 93,
      tyreManagement: 94,
      consistency: 96,
      wetWeatherSkill: 88,
      aggressionIndex: 72,
      incidentProneness: 95,
      loyalty: 99,
      potential: 91,
      reputation: 88,
      specialties: ['DRS Timing', 'Clean Defender'],
      trait: DRIVER_TRAITS.DRS_ASSASSIN,
    },
    car: CARS.Williams,
    rookie: false,
    age: 29,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 6000000,
    form: 0,
    happiness: 80,
    morale: 85,
    careerHistory: { 2025: 'Williams Racing' },
  },
  {
    id: 6,
    name: 'Carlos Sainz',
    shortName: 'SAI',
    number: 55,
    driverSkills: {
      overall: 86,
      qualifyingPace: 89,
      raceCraft: 92,
      tyreManagement: 94,
      consistency: 91,
      wetWeatherSkill: 86,
      aggressionIndex: 72,
      incidentProneness: 96,
      loyalty: 89,
      potential: 90,
      reputation: 90,
      specialties: ['Smooth Operator', 'Tyre Saving Under Pressure'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.Williams,
    rookie: false,
    age: 30,
    contractExpiresIn: 3,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 14000000,
    form: 0,
    happiness: 75,
    morale: 78,
    careerHistory: { 2025: 'Williams Racing' },
  },

  // Aston Martin Aramco Formula One Team
  {
    id: 9,
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    driverSkills: {
      overall: 89,
      qualifyingPace: 95,
      raceCraft: 99,
      tyreManagement: 96,
      consistency: 90,
      wetWeatherSkill: 97,
      aggressionIndex: 92,
      incidentProneness: 92,
      loyalty: 85,
      potential: 66,
      reputation: 97,
      specialties: ['Night Hunter', 'Defensive Genius'],
      trait: DRIVER_TRAITS.NIGHT_OPS,
    },
    car: CARS.AstonMartin,
    rookie: false,
    age: 43,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 25000000,
    form: 0,
    happiness: 90,
    morale: 92,
    careerHistory: { 2025: 'Aston Martin Aramco Formula One Team' },
  },
  {
    id: 10,
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    driverSkills: {
      overall: 75,
      qualifyingPace: 72,
      raceCraft: 83,
      tyreManagement: 77,
      consistency: 74,
      wetWeatherSkill: 90,
      aggressionIndex: 78,
      incidentProneness: 82,
      loyalty: 100,
      potential: 83,
      reputation: 76,
      specialties: ['Launch Specialist', 'Risk-on Overtakes'],
      trait: DRIVER_TRAITS.ROCKET_START,
    },
    car: CARS.AstonMartin,
    rookie: false,
    age: 26,
    contractExpiresIn: 3,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 4000000,
    form: 0,
    happiness: 65,
    morale: 70,
    careerHistory: { 2025: 'Aston Martin Aramco Formula One Team' },
  },

  // Stake F1 Team Kick Sauber
  {
    id: 18,
    name: 'Nico Hülkenberg',
    shortName: 'HUL',
    number: 27,
    driverSkills: {
      overall: 86,
      qualifyingPace: 88,
      raceCraft: 89,
      tyreManagement: 87,
      consistency: 93,
      wetWeatherSkill: 94,
      aggressionIndex: 66,
      incidentProneness: 95,
      loyalty: 90,
      potential: 73,
      reputation: 83,
      specialties: ['Quali Punch', 'Safety-Car Restarts'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.Sauber,
    rookie: false,
    age: 37,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 5000000,
    form: 0,
    happiness: 78,
    morale: 80,
    careerHistory: { 2025: 'Stake F1 Team Kick Sauber' },
  },
  {
    id: 22,
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    driverSkills: {
      overall: 77,
      qualifyingPace: 89,
      raceCraft: 74,
      tyreManagement: 76,
      consistency: 77,
      wetWeatherSkill: 78,
      aggressionIndex: 79,
      incidentProneness: 79,
      loyalty: 96,
      potential: 94,
      reputation: 70,
      specialties: ['Quali Flash', 'Junior Composure'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.Sauber,
    rookie: true,
    age: 20,
    contractExpiresIn: 2,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 1000000,
    form: 0,
    happiness: 85,
    morale: 85,
    careerHistory: { 2025: 'Stake F1 Team Kick Sauber' },
  },

  // Visa Cash App RB Formula One Team
  {
    id: 21,
    name: 'Isack Hadjar',
    shortName: 'HAD',
    number: 6,
    driverSkills: {
      overall: 86,
      qualifyingPace: 90,
      raceCraft: 86,
      tyreManagement: 84,
      consistency: 89,
      wetWeatherSkill: 82,
      aggressionIndex: 83,
      incidentProneness: 85,
      loyalty: 95,
      potential: 96,
      reputation: 71,
      specialties: ['Late-Brake Heroics', 'High-Risk Duels'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.RB,
    rookie: true,
    age: 20,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 750000,
    form: 0,
    happiness: 85,
    morale: 85,
    careerHistory: { 2025: 'Visa Cash App RB Formula One Team' },
  },
  {
    id: 25,
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    driverSkills: {
      overall: 80,
      qualifyingPace: 82,
      raceCraft: 83,
      tyreManagement: 80,
      consistency: 78,
      wetWeatherSkill: 80,
      aggressionIndex: 84,
      incidentProneness: 78,
      loyalty: 95,
      potential: 93,
      reputation: 74,
      specialties: ['Race Pace Growth', 'Tyre Care Basics'],
      trait: DRIVER_TRAITS.MR_CONSISTENT,
    },
    car: CARS.RB,
    rookie: true,
    age: 23,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 1500000,
    form: 0,
    happiness: 82,
    morale: 84,
    careerHistory: { 2025: 'Visa Cash App RB Formula One Team' },
  },

  // MoneyGram Haas F1 Team
  {
    id: 11,
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    driverSkills: {
      overall: 83,
      qualifyingPace: 86,
      raceCraft: 87,
      tyreManagement: 90,
      consistency: 87,
      wetWeatherSkill: 93,
      aggressionIndex: 88,
      incidentProneness: 80,
      loyalty: 81,
      potential: 87,
      reputation: 84,
      specialties: ['Defensive Lines', 'Wet Stability'],
      trait: DRIVER_TRAITS.THE_WALL,
    },
    car: CARS.Haas,
    rookie: false,
    age: 28,
    contractExpiresIn: 2,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 7000000,
    form: 0,
    happiness: 70,
    morale: 72,
    careerHistory: { 2025: 'MoneyGram Haas F1 Team' },
  },
  {
    id: 24,
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    driverSkills: {
      overall: 78,
      qualifyingPace: 87,
      raceCraft: 77,
      tyreManagement: 78,
      consistency: 80,
      wetWeatherSkill: 80,
      aggressionIndex: 77,
      incidentProneness: 82,
      loyalty: 97,
      potential: 95,
      reputation: 71,
      specialties: ['Quali Punch', 'Rookie Calm'],
      trait: DRIVER_TRAITS.CLUTCH_PERFORMER,
    },
    car: CARS.Haas,
    rookie: true,
    age: 20,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 1000000,
    form: 0,
    happiness: 85,
    morale: 85,
    careerHistory: { 2025: 'MoneyGram Haas F1 Team' },
  },

  // BWT Alpine F1 Team
  {
    id: 12,
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    driverSkills: {
      overall: 84,
      qualifyingPace: 87,
      raceCraft: 84,
      tyreManagement: 83,
      consistency: 82,
      wetWeatherSkill: 91,
      aggressionIndex: 81,
      incidentProneness: 84,
      loyalty: 93,
      potential: 86,
      reputation: 85,
      specialties: ['Launch Punch', 'Wet Aggression'],
      trait: DRIVER_TRAITS.ROCKET_START,
    },
    car: CARS.Alpine,
    rookie: false,
    age: 29,
    contractExpiresIn: 2,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 9000000,
    form: 0,
    happiness: 68,
    morale: 70,
    careerHistory: { 2025: 'BWT Alpine F1 Team' },
  },
  {
    id: 32,
    name: 'Franco Colapinto',
    shortName: 'COL',
    number: 43,
    driverSkills: {
      overall: 70,
      qualifyingPace: 72,
      raceCraft: 71,
      tyreManagement: 70,
      consistency: 72,
      wetWeatherSkill: 72,
      aggressionIndex: 73,
      incidentProneness: 84,
      loyalty: 94,
      potential: 89,
      reputation: 66,
      specialties: ['Rookie Patience', 'Clean Laps'],
      trait: DRIVER_TRAITS.MR_CONSISTENT,
    },
    car: CARS.Alpine,
    rookie: true,
    age: 22,
    contractExpiresIn: 1,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Active',
    peakDsv: 0,
    salary: 750000,
    form: 0,
    happiness: 85,
    morale: 85,
    careerHistory: { 2025: 'BWT Alpine F1 Team' },
  },

  // --- FREE AGENTS AT START ---
  {
    id: 28,
    name: 'Sergio Pérez',
    shortName: 'PER',
    number: 11,
    driverSkills: {
      overall: 89,
      qualifyingPace: 86,
      raceCraft: 93,
      tyreManagement: 96,
      consistency: 88,
      wetWeatherSkill: 90,
      aggressionIndex: 71,
      incidentProneness: 72,
      loyalty: 81,
      potential: 76,
      reputation: 86,
      specialties: ['Tyre Whisperer', 'Late-Race Pace', 'Street Circuit Calm'],
      trait: DRIVER_TRAITS.TYRE_WHISPERER,
    },
    car: CARS.RedBull,
    rookie: false,
    age: 35,
    contractExpiresIn: 0,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Free Agent',
    peakDsv: 0,
    salary: 12000000,
    form: 0,
    happiness: 75,
    morale: 75,
    careerHistory: { 2025: 'Free Agent' },
  },
  {
    id: 31,
    name: 'Kevin Magnussen',
    shortName: 'MAG',
    number: 20,
    driverSkills: {
      overall: 81,
      qualifyingPace: 83,
      raceCraft: 82,
      tyreManagement: 79,
      consistency: 78,
      wetWeatherSkill: 84,
      aggressionIndex: 92,
      incidentProneness: 90,
      loyalty: 85,
      potential: 79,
      reputation: 80,
      specialties: ['Divebomb Specialist', 'Defensive Elbows'],
      trait: DRIVER_TRAITS.ERROR_PRONE,
    },
    car: CARS.Haas,
    rookie: false,
    age: 32,
    contractExpiresIn: 0,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Free Agent',
    peakDsv: 0,
    salary: 4000000,
    form: 0,
    happiness: 75,
    morale: 75,
    careerHistory: { 2025: 'Free Agent' },
  },
  {
    id: 27,
    name: 'Jack Doohan',
    shortName: 'DOO',
    number: 7,
    driverSkills: {
      overall: 70,
      qualifyingPace: 72,
      raceCraft: 71,
      tyreManagement: 69,
      consistency: 71,
      wetWeatherSkill: 71,
      aggressionIndex: 74,
      incidentProneness: 85,
      loyalty: 94,
      potential: 88,
      reputation: 67,
      specialties: ['Quali Builder', 'Tyre Learner'],
      trait: DRIVER_TRAITS.MR_CONSISTENT,
    },
    car: CARS.Alpine,
    rookie: true,
    age: 22,
    contractExpiresIn: 0,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Free Agent',
    peakDsv: 0,
    salary: 750000,
    form: 0,
    happiness: 75,
    morale: 75,
    careerHistory: { 2025: 'Free Agent' },
  },
  {
    id: 29,
    name: 'Valtteri Bottas',
    shortName: 'BOT',
    number: 77,
    driverSkills: {
      overall: 86,
      qualifyingPace: 89,
      raceCraft: 85,
      tyreManagement: 87,
      consistency: 89,
      wetWeatherSkill: 86,
      aggressionIndex: 62,
      incidentProneness: 55,
      loyalty: 82,
      potential: 78,
      reputation: 82,
      specialties: ['Fuel & Tyre Caller', 'Lap-Delta Discipline'],
      trait: DRIVER_TRAITS.STRATEGY_SAVANT,
    },
    car: CARS.Sauber,
    rookie: false,
    age: 35,
    contractExpiresIn: 0,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Free Agent',
    peakDsv: 0,
    salary: 10000000,
    form: 0,
    happiness: 75,
    morale: 75,
    careerHistory: { 2025: 'Free Agent' },
  },
  {
    id: 30,
    name: 'Guanyu Zhou',
    shortName: 'ZHO',
    number: 24,
    driverSkills: {
      overall: 80,
      qualifyingPace: 79,
      raceCraft: 81,
      tyreManagement: 84,
      consistency: 85,
      wetWeatherSkill: 80,
      aggressionIndex: 66,
      incidentProneness: 62,
      loyalty: 79,
      potential: 85,
      reputation: 75,
      specialties: ['Tyre Economy', 'Calm Racecraft'],
      trait: DRIVER_TRAITS.MR_CONSISTENT,
    },
    car: CARS.Sauber,
    rookie: false,
    age: 26,
    contractExpiresIn: 0,
    careerWins: 0,
    careerPodiums: 0,
    championships: 0,
    status: 'Free Agent',
    peakDsv: 0,
    salary: 2000000,
    form: 0,
    happiness: 75,
    morale: 75,
    careerHistory: { 2025: 'Free Agent' },
  },
];

export const INITIAL_DRIVERS: InitialDriver[] = DRIVER_SEED.map(driver => ({
  ...driver,
  carLink: DRIVER_CAR_LINKS[driver.id] || { compatibility: 60, adaptation: 60, notes: 'Baseline fit' },
}));
