
import { InitialDriver } from '../types';
import { CARS } from './teams';
import { DRIVER_TRAITS } from './traits';

// The roster is now set to the definitive 2025 season lineup.
export const INITIAL_DRIVERS: InitialDriver[] = [
  // McLaren Formula 1 Team
  { id: 8, name: 'Oscar Piastri', shortName: 'PIA', number: 81, driverSkills: { overall: 98, qualifyingPace: 97, raceCraft: 96, tyreManagement: 95, consistency: 99, wetWeatherSkill: 90, aggressionIndex: 75, incidentProneness: 98, loyalty: 99, potential: 99, reputation: 90, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.McLaren, rookie: false, age: 24, contractExpiresIn: 3, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 6000000, form: 0, happiness: 85, morale: 90, careerHistory: { 2025: 'McLaren Formula 1 Team' } },
  { id: 7, name: 'Lando Norris', shortName: 'NOR', number: 4, driverSkills: { overall: 97, qualifyingPace: 96, raceCraft: 90, tyreManagement: 98, consistency: 92, wetWeatherSkill: 96, aggressionIndex: 80, incidentProneness: 90, loyalty: 100, potential: 98, reputation: 93, trait: DRIVER_TRAITS.RAIN_MASTER }, car: CARS.McLaren, rookie: false, age: 25, contractExpiresIn: 4, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 30000000, form: 0, happiness: 90, morale: 88, careerHistory: { 2025: 'McLaren Formula 1 Team' } },
  
  // Oracle Red Bull Racing
  { id: 1, name: 'Max Verstappen', shortName: 'VER', number: 1, driverSkills: { overall: 96, qualifyingPace: 99, raceCraft: 98, tyreManagement: 85, consistency: 93, wetWeatherSkill: 99, aggressionIndex: 95, incidentProneness: 88, loyalty: 95, potential: 97, reputation: 99, trait: DRIVER_TRAITS.THE_OVERTAKER }, car: CARS.RedBull, rookie: false, age: 27, contractExpiresIn: 4, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 55000000, form: 0, happiness: 95, morale: 95, careerHistory: { 2025: 'Oracle Red Bull Racing' } },
  { id: 13, name: 'Yuki Tsunoda', shortName: 'TSU', number: 22, driverSkills: { overall: 76, qualifyingPace: 78, raceCraft: 79, tyreManagement: 72, consistency: 74, wetWeatherSkill: 77, aggressionIndex: 85, incidentProneness: 80, loyalty: 95, potential: 89, reputation: 78, trait: DRIVER_TRAITS.ERROR_PRONE }, car: CARS.RedBull, rookie: false, age: 25, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 2500000, form: 0, happiness: 70, morale: 75, careerHistory: { 2025: 'Oracle Red Bull Racing' } },
  
  // Mercedes-AMG Petronas Formula One Team
  { id: 4, name: 'George Russell', shortName: 'RUS', number: 63, driverSkills: { overall: 92, qualifyingPace: 94, raceCraft: 90, tyreManagement: 88, consistency: 95, wetWeatherSkill: 91, aggressionIndex: 78, incidentProneness: 85, loyalty: 98, potential: 95, reputation: 92, trait: DRIVER_TRAITS.MR_SATURDAY }, car: CARS.Mercedes, rookie: false, age: 27, contractExpiresIn: 2, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 18000000, form: 0, happiness: 80, morale: 82, careerHistory: { 2025: 'Mercedes-AMG Petronas Formula One Team' } },
  { id: 23, name: 'Andrea Kimi Antonelli', shortName: 'ANT', number: 12, driverSkills: { overall: 80, qualifyingPace: 84, raceCraft: 80, tyreManagement: 78, consistency: 82, wetWeatherSkill: 81, aggressionIndex: 86, incidentProneness: 81, loyalty: 98, potential: 99, reputation: 70, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.Mercedes, rookie: true, age: 19, contractExpiresIn: 3, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 1000000, form: 0, happiness: 85, morale: 85, careerHistory: { 2025: 'Mercedes-AMG Petronas Formula One Team' } },

  // Scuderia Ferrari
  { id: 5, name: 'Charles Leclerc', shortName: 'LEC', number: 16, driverSkills: { overall: 91, qualifyingPace: 98, raceCraft: 92, tyreManagement: 89, consistency: 85, wetWeatherSkill: 84, aggressionIndex: 85, incidentProneness: 82, loyalty: 100, potential: 96, reputation: 94, trait: DRIVER_TRAITS.MR_SATURDAY }, car: CARS.Ferrari, rookie: false, age: 27, contractExpiresIn: 5, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 35000000, form: 0, happiness: 88, morale: 85, careerHistory: { 2025: 'Scuderia Ferrari' } },
  { id: 3, name: 'Lewis Hamilton', shortName: 'HAM', number: 44, driverSkills: { overall: 90, qualifyingPace: 88, raceCraft: 97, tyreManagement: 97, consistency: 90, wetWeatherSkill: 98, aggressionIndex: 70, incidentProneness: 92, loyalty: 90, potential: 70, reputation: 98, trait: DRIVER_TRAITS.TYRE_WHISPERER }, car: CARS.Ferrari, rookie: false, age: 40, contractExpiresIn: 2, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 55000000, form: 0, happiness: 92, morale: 90, careerHistory: { 2025: 'Scuderia Ferrari' } },
  
  // Williams Racing
  { id: 19, name: 'Alexander Albon', shortName: 'ALB', number: 23, driverSkills: { overall: 89, qualifyingPace: 90, raceCraft: 92, tyreManagement: 93, consistency: 96, wetWeatherSkill: 88, aggressionIndex: 70, incidentProneness: 94, loyalty: 99, potential: 90, reputation: 87, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.Williams, rookie: false, age: 29, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 6000000, form: 0, happiness: 80, morale: 85, careerHistory: { 2025: 'Williams Racing' } },
  { id: 6, name: 'Carlos Sainz', shortName: 'SAI', number: 55, driverSkills: { overall: 84, qualifyingPace: 88, raceCraft: 91, tyreManagement: 92, consistency: 90, wetWeatherSkill: 85, aggressionIndex: 70, incidentProneness: 96, loyalty: 88, potential: 88, reputation: 89, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.Williams, rookie: false, age: 30, contractExpiresIn: 3, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 14000000, form: 0, happiness: 75, morale: 78, careerHistory: { 2025: 'Williams Racing' } },

  // Aston Martin Aramco Formula One Team
  { id: 9, name: 'Fernando Alonso', shortName: 'ALO', number: 14, driverSkills: { overall: 88, qualifyingPace: 95, raceCraft: 99, tyreManagement: 96, consistency: 88, wetWeatherSkill: 97, aggressionIndex: 92, incidentProneness: 91, loyalty: 85, potential: 65, reputation: 97, trait: DRIVER_TRAITS.THE_WALL }, car: CARS.AstonMartin, rookie: false, age: 43, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 25000000, form: 0, happiness: 90, morale: 92, careerHistory: { 2025: 'Aston Martin Aramco Formula One Team' } },
  { id: 10, name: 'Lance Stroll', shortName: 'STR', number: 18, driverSkills: { overall: 74, qualifyingPace: 70, raceCraft: 82, tyreManagement: 75, consistency: 72, wetWeatherSkill: 89, aggressionIndex: 78, incidentProneness: 82, loyalty: 100, potential: 82, reputation: 75, trait: DRIVER_TRAITS.ROCKET_START }, car: CARS.AstonMartin, rookie: false, age: 26, contractExpiresIn: 3, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 4000000, form: 0, happiness: 65, morale: 70, careerHistory: { 2025: 'Aston Martin Aramco Formula One Team' } },

  // Stake F1 Team Kick Sauber
  { id: 18, name: 'Nico Hülkenberg', shortName: 'HUL', number: 27, driverSkills: { overall: 86, qualifyingPace: 87, raceCraft: 88, tyreManagement: 86, consistency: 92, wetWeatherSkill: 94, aggressionIndex: 65, incidentProneness: 95, loyalty: 90, potential: 72, reputation: 82, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.Sauber, rookie: false, age: 37, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 5000000, form: 0, happiness: 78, morale: 80, careerHistory: { 2025: 'Stake F1 Team Kick Sauber' } },
  { id: 22, name: 'Gabriel Bortoleto', shortName: 'BOR', number: 5, driverSkills: { overall: 75, qualifyingPace: 88, raceCraft: 72, tyreManagement: 74, consistency: 75, wetWeatherSkill: 76, aggressionIndex: 78, incidentProneness: 80, loyalty: 96, potential: 93, reputation: 68, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.Sauber, rookie: true, age: 20, contractExpiresIn: 2, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 1000000, form: 0, happiness: 85, morale: 85, careerHistory: { 2025: 'Stake F1 Team Kick Sauber' } },
  
  // Visa Cash App RB Formula One Team
  { id: 21, name: 'Isack Hadjar', shortName: 'HAD', number: 6, driverSkills: { overall: 85, qualifyingPace: 89, raceCraft: 85, tyreManagement: 83, consistency: 88, wetWeatherSkill: 80, aggressionIndex: 82, incidentProneness: 86, loyalty: 95, potential: 95, reputation: 69, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.RB, rookie: true, age: 20, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 750000, form: 0, happiness: 85, morale: 85, careerHistory: { 2025: 'Visa Cash App RB Formula One Team' } },
  { id: 25, name: 'Liam Lawson', shortName: 'LAW', number: 30, driverSkills: { overall: 78, qualifyingPace: 80, raceCraft: 81, tyreManagement: 79, consistency: 75, wetWeatherSkill: 78, aggressionIndex: 84, incidentProneness: 79, loyalty: 95, potential: 92, reputation: 72, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.RB, rookie: true, age: 23, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 1500000, form: 0, happiness: 82, morale: 84, careerHistory: { 2025: 'Visa Cash App RB Formula One Team' } },

  // MoneyGram Haas F1 Team
  { id: 11, name: 'Esteban Ocon', shortName: 'OCO', number: 31, driverSkills: { overall: 81, qualifyingPace: 85, raceCraft: 86, tyreManagement: 88, consistency: 85, wetWeatherSkill: 92, aggressionIndex: 88, incidentProneness: 80, loyalty: 80, potential: 86, reputation: 83, trait: DRIVER_TRAITS.THE_WALL }, car: CARS.Haas, rookie: false, age: 28, contractExpiresIn: 2, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 7000000, form: 0, happiness: 70, morale: 72, careerHistory: { 2025: 'MoneyGram Haas F1 Team' } },
  { id: 24, name: 'Oliver Bearman', shortName: 'BEA', number: 87, driverSkills: { overall: 77, qualifyingPace: 86, raceCraft: 75, tyreManagement: 76, consistency: 78, wetWeatherSkill: 79, aggressionIndex: 75, incidentProneness: 83, loyalty: 97, potential: 94, reputation: 69, trait: DRIVER_TRAITS.CLUTCH_PERFORMER }, car: CARS.Haas, rookie: true, age: 20, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 1000000, form: 0, happiness: 85, morale: 85, careerHistory: { 2025: 'MoneyGram Haas F1 Team' } },

  // BWT Alpine F1 Team
  { id: 12, name: 'Pierre Gasly', shortName: 'GAS', number: 10, driverSkills: { overall: 82, qualifyingPace: 86, raceCraft: 83, tyreManagement: 82, consistency: 80, wetWeatherSkill: 90, aggressionIndex: 80, incidentProneness: 84, loyalty: 92, potential: 85, reputation: 84, trait: DRIVER_TRAITS.ROCKET_START }, car: CARS.Alpine, rookie: false, age: 29, contractExpiresIn: 2, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 9000000, form: 0, happiness: 68, morale: 70, careerHistory: { 2025: 'BWT Alpine F1 Team' } },
  { id: 32, name: 'Franco Colapinto', shortName: 'COL', number: 43, driverSkills: { overall: 68, qualifyingPace: 70, raceCraft: 69, tyreManagement: 68, consistency: 70, wetWeatherSkill: 70, aggressionIndex: 72, incidentProneness: 85, loyalty: 94, potential: 88, reputation: 65, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.Alpine, rookie: true, age: 22, contractExpiresIn: 1, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Active', peakDsv: 0, salary: 750000, form: 0, happiness: 85, morale: 85, careerHistory: { 2025: 'BWT Alpine F1 Team' } },
  
  // --- FREE AGENTS AT START ---
  { id: 28, name: 'Sergio Pérez', shortName: 'PER', number: 11, driverSkills: { overall: 88, qualifyingPace: 85, raceCraft: 92, tyreManagement: 94, consistency: 87, wetWeatherSkill: 89, aggressionIndex: 70, incidentProneness: 70, loyalty: 80, potential: 75, reputation: 86, trait: DRIVER_TRAITS.TYRE_WHISPERER }, car: CARS.RedBull, rookie: false, age: 35, contractExpiresIn: 0, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Free Agent', peakDsv: 0, salary: 12000000, form: 0, happiness: 75, morale: 75, careerHistory: { 2025: 'Free Agent' } },
  { id: 31, name: 'Kevin Magnussen', shortName: 'MAG', number: 20, driverSkills: { overall: 80, qualifyingPace: 82, raceCraft: 81, tyreManagement: 78, consistency: 77, wetWeatherSkill: 83, aggressionIndex: 90, incidentProneness: 90, loyalty: 85, potential: 78, reputation: 79, trait: DRIVER_TRAITS.ERROR_PRONE }, car: CARS.Haas, rookie: false, age: 32, contractExpiresIn: 0, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Free Agent', peakDsv: 0, salary: 4000000, form: 0, happiness: 75, morale: 75, careerHistory: { 2025: 'Free Agent' } },
  { id: 27, name: 'Jack Doohan', shortName: 'DOO', number: 7, driverSkills: { overall: 67, qualifyingPace: 69, raceCraft: 68, tyreManagement: 67, consistency: 69, wetWeatherSkill: 69, aggressionIndex: 73, incidentProneness: 86, loyalty: 94, potential: 87, reputation: 66, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.Alpine, rookie: true, age: 22, contractExpiresIn: 0, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Free Agent', peakDsv: 0, salary: 750000, form: 0, happiness: 75, morale: 75, careerHistory: { 2025: 'Free Agent' } },
  { id: 29, name: 'Valtteri Bottas', shortName: 'BOT', number: 77, driverSkills: { overall: 85, qualifyingPace: 88, raceCraft: 84, tyreManagement: 86, consistency: 88, wetWeatherSkill: 85, aggressionIndex: 60, incidentProneness: 50, loyalty: 80, potential: 76, reputation: 81, trait: DRIVER_TRAITS.MR_SATURDAY }, car: CARS.Sauber, rookie: false, age: 35, contractExpiresIn: 0, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Free Agent', peakDsv: 0, salary: 10000000, form: 0, happiness: 75, morale: 75, careerHistory: { 2025: 'Free Agent' } },
  { id: 30, name: 'Guanyu Zhou', shortName: 'ZHO', number: 24, driverSkills: { overall: 79, qualifyingPace: 78, raceCraft: 80, tyreManagement: 82, consistency: 84, wetWeatherSkill: 79, aggressionIndex: 65, incidentProneness: 60, loyalty: 78, potential: 84, reputation: 74, trait: DRIVER_TRAITS.MR_CONSISTENT }, car: CARS.Sauber, rookie: false, age: 26, contractExpiresIn: 0, careerWins: 0, careerPodiums: 0, championships: 0, status: 'Free Agent', peakDsv: 0, salary: 2000000, form: 0, happiness: 75, morale: 75, careerHistory: { 2025: 'Free Agent' } },
];
