import { Track, TrackCharacteristic, SecondaryTrackCharacteristic } from '../types';

// Wet Session Probability data sourced from the user-provided 2025 F1 Season Weather Probabilities report.
// All other data is a combination of the user-provided text and inferred simulation parameters.
export const FULL_SEASON_TRACKS: Track[] = [
    { 
        name: 'Albert Park Circuit', 
        description: "A semi-permanent street circuit located in the picturesque Albert Park, this track is known for its relatively smooth surface and flowing nature. It's a challenging mix of medium and high-speed corners, with several chicanes and short straights.", 
        laps: 58, 
        baseLapTime: 80, 
        downforceLevel: 4, 
        tyreStress: 3, 
        brakeWear: 4, 
        powerSensitivity: 3, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.67, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 19.5, 
        primaryCharacteristic: 'High-Speed Flow', 
        secondaryCharacteristic: 'Braking Stability', 
        riskTier: 2, 
        wetSessionProbability: 0.25, 
        pastWinners: ['Carlos Sainz Jr.', 'Carlos Sainz Jr.', 'Max Verstappen', 'Charles Leclerc', 'Valtteri Bottas'] 
    },
    { 
        name: 'Shanghai International Circuit', 
        description: "A modern circuit with a unique design, Shanghai is known for its long, snail-like opening corners (Turns 1 and 2) and the massive back straight, which is over a kilometre long. The track features a good mix of high-speed corners, tight hairpins, and technical sections.", 
        laps: 56, 
        baseLapTime: 92, 
        downforceLevel: 4, 
        tyreStress: 4, 
        brakeWear: 3, 
        powerSensitivity: 4, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.75, 
        virtualSafetyCarProbability: 0.75, 
        pitLaneTimeLoss: 23.9, 
        primaryCharacteristic: 'High-Speed Aero', 
        secondaryCharacteristic: 'Front-Limited', 
        riskTier: 2, 
        wetSessionProbability: 0.40, 
        technicalDirective: 'WingFlexV1', 
        pastWinners: ['Max Verstappen', 'Lewis Hamilton', 'Daniel Ricciardo', 'Lewis Hamilton', 'Nico Rosberg'] 
    },
    { 
        name: 'Suzuka International Racing Course', 
        description: "A true driver's circuit, Suzuka is a favourite among many on the grid. Its unique figure-of-eight layout features a challenging mix of high-speed corners, technical sections, and significant elevation changes. The famous 'S' Curves in the first sector and the iconic 130R corner are highlights.", 
        laps: 53, 
        baseLapTime: 91, 
        downforceLevel: 5, 
        tyreStress: 5, 
        brakeWear: 2, 
        powerSensitivity: 4, 
        overtakingDifficulty: 4, 
        drsEffectiveness: 3, 
        safetyCarProbability: 0.50, 
        virtualSafetyCarProbability: 0.67, 
        pitLaneTimeLoss: 22.0, 
        primaryCharacteristic: 'High-Speed Aero', 
        secondaryCharacteristic: null, 
        riskTier: 3, 
        wetSessionProbability: 0.45, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Valtteri Bottas', 'Lewis Hamilton'] 
    },
    { 
        name: 'Bahrain International Circuit', 
        description: "A modern, purpose-built circuit located in the desert, Bahrain is characterized by its long straights and heavy braking zones, making it a power-sensitive track. The layout features a mix of tight hairpins and fast, sweeping corners. The track surface is known for being abrasive.", 
        laps: 57, 
        baseLapTime: 95, 
        downforceLevel: 3, 
        tyreStress: 5, 
        brakeWear: 4, 
        powerSensitivity: 4, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.63, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 23.2, 
        primaryCharacteristic: 'Power & Traction', 
        secondaryCharacteristic: 'Rear-Limited', 
        riskTier: 3, 
        wetSessionProbability: 0.05, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Charles Leclerc', 'Lewis Hamilton'] 
    },
    { 
        name: 'Jeddah Corniche Circuit', 
        description: "The fastest street circuit on the F1 calendar, Jeddah is a thrilling and demanding track that winds its way along the Red Sea coastline. It's characterized by a series of high-speed, flowing corners and long straights, with an average speed that rivals some permanent circuits.", 
        laps: 50, 
        baseLapTime: 91, 
        downforceLevel: 2, 
        tyreStress: 3, 
        brakeWear: 3, 
        powerSensitivity: 5, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 4, 
        safetyCarProbability: 1.00, 
        virtualSafetyCarProbability: 0.67, 
        pitLaneTimeLoss: 20.1, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'High-Speed Flow', 
        riskTier: 3, 
        wetSessionProbability: 0.05, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Sergio Pérez', 'Max Verstappen'] 
    },
    { 
        name: 'Miami International Autodrome', 
        description: "A temporary circuit built around the Hard Rock Stadium, the Miami International Autodrome is a fast and flowing track with a mix of high-speed straights and a tight, technical section in the final sector. The circuit has been designed to promote close racing.", 
        laps: 57, 
        baseLapTime: 88, 
        downforceLevel: 3, 
        tyreStress: 3, 
        brakeWear: 3, 
        powerSensitivity: 4, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.67, 
        virtualSafetyCarProbability: 0.67, 
        pitLaneTimeLoss: 21.5, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'Low-Speed Technical', 
        riskTier: 2, 
        wetSessionProbability: 0.35, 
        pastWinners: ['Lando Norris', 'Max Verstappen', 'Max Verstappen'] 
    },
    { 
        name: 'Autodromo Enzo e Dino Ferrari', 
        description: "An old-school, historic circuit nestled in the Emilia-Romagna region, Imola is a narrow, fast, and flowing track with significant elevation changes. It's a challenging circuit that punishes mistakes, with gravel traps and grass verges lining the track.", 
        laps: 63, 
        baseLapTime: 75, 
        downforceLevel: 4, 
        tyreStress: 3, 
        brakeWear: 3, 
        powerSensitivity: 3, 
        overtakingDifficulty: 4, 
        drsEffectiveness: 3, 
        safetyCarProbability: 0.75, 
        virtualSafetyCarProbability: 0.25, 
        pitLaneTimeLoss: 25.0, 
        primaryCharacteristic: 'High-Speed Flow', 
        secondaryCharacteristic: 'Kerb Riding', 
        riskTier: 1, 
        wetSessionProbability: 0.30, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton', 'Michael Schumacher'] 
    },
    { 
        name: 'Circuit de Monaco', 
        description: "The jewel in the F1 crown, Monaco is the most iconic and glamorous race on the calendar. The narrow, twisting street circuit is the ultimate test of driver skill and precision. There is absolutely no room for error, with the barriers lining the entire track.", 
        laps: 78, 
        baseLapTime: 73, 
        downforceLevel: 5, 
        tyreStress: 1, 
        brakeWear: 2, 
        powerSensitivity: 1, 
        overtakingDifficulty: 5, 
        drsEffectiveness: 1, 
        safetyCarProbability: 0.85, 
        virtualSafetyCarProbability: 0.29, 
        pitLaneTimeLoss: 19.4, 
        primaryCharacteristic: 'Max Downforce / Low-Speed', 
        secondaryCharacteristic: 'Mechanical Grip', 
        riskTier: 1, 
        wetSessionProbability: 0.25, 
        pastWinners: ['Charles Leclerc', 'Max Verstappen', 'Sergio Pérez', 'Max Verstappen', 'Lewis Hamilton'] 
    },
    { 
        name: 'Circuit Gilles Villeneuve', 
        description: "A semi-permanent circuit on the man-made Île Notre-Dame, the Circuit Gilles Villeneuve is a fast and flowing track with long straights and chicanes. It's known for being tough on brakes and for its close, unforgiving walls.", 
        laps: 70, 
        baseLapTime: 73, 
        downforceLevel: 2, 
        tyreStress: 2, 
        brakeWear: 5, 
        powerSensitivity: 4, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.83, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 18.4, 
        primaryCharacteristic: 'Power & Traction', 
        secondaryCharacteristic: 'Braking Stability', 
        riskTier: 2, 
        wetSessionProbability: 0.50, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton', 'Sebastian Vettel'] 
    },
    { 
        name: 'Circuit de Barcelona-Catalunya', 
        description: "A well-known and respected test track, the Circuit de Barcelona-Catalunya is a true all-rounder, with a mix of high-speed corners, a long straight, and a slow, technical final sector. It's a track that provides a good measure of a car's aerodynamic performance.", 
        laps: 66, 
        baseLapTime: 76, 
        downforceLevel: 4, 
        tyreStress: 5, 
        brakeWear: 3, 
        powerSensitivity: 3, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.38, 
        virtualSafetyCarProbability: 0.25, 
        pitLaneTimeLoss: 22.2, 
        primaryCharacteristic: 'High-Speed Aero', 
        secondaryCharacteristic: 'Front-Limited', 
        riskTier: 3, 
        wetSessionProbability: 0.15, 
        technicalDirective: 'WingFlexV2', 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Lewis Hamilton', 'Lewis Hamilton', 'Lewis Hamilton'] 
    },
    { 
        name: 'Red Bull Ring', 
        description: "Set in the stunning Styrian mountains, the Red Bull Ring is a short, fast, and undulating circuit with a simple but challenging layout. It features long straights, heavy braking zones, and several fast, flowing corners.", 
        laps: 71, 
        baseLapTime: 66, 
        downforceLevel: 3, 
        tyreStress: 3, 
        brakeWear: 4, 
        powerSensitivity: 4, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.38, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 20.3, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'Traction', 
        riskTier: 1, 
        wetSessionProbability: 0.55, 
        pastWinners: ['Max Verstappen', 'Charles Leclerc', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton'] 
    },
    { 
        name: 'Silverstone Circuit', 
        description: "The historic home of the British Grand Prix, Silverstone is a fast and flowing circuit with a legendary sequence of high-speed corners, including Maggots, Becketts, and Chapel. It's a true test of a car's aerodynamic prowess and a driver's bravery.", 
        laps: 52, 
        baseLapTime: 89, 
        downforceLevel: 5, 
        tyreStress: 5, 
        brakeWear: 1, 
        powerSensitivity: 4, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.88, 
        virtualSafetyCarProbability: 0.13, 
        pitLaneTimeLoss: 19.9, 
        primaryCharacteristic: 'High-Speed Aero', 
        secondaryCharacteristic: null, 
        riskTier: 3, 
        wetSessionProbability: 0.55, 
        pastWinners: ['Max Verstappen', 'Carlos Sainz Jr.', 'Lewis Hamilton', 'Max Verstappen', 'Lewis Hamilton'] 
    },
    { 
        name: 'Hungaroring', 
        description: "Often referred to as 'Monaco without the walls,' the Hungaroring is a tight, twisting, and technical circuit with a relentless series of corners. It's a low-speed track where aerodynamic downforce is crucial.", 
        laps: 70, 
        baseLapTime: 77, 
        downforceLevel: 5, 
        tyreStress: 4, 
        brakeWear: 2, 
        powerSensitivity: 2, 
        overtakingDifficulty: 5, 
        drsEffectiveness: 2, 
        safetyCarProbability: 0.50, 
        virtualSafetyCarProbability: 0.25, 
        pitLaneTimeLoss: 21.0, 
        primaryCharacteristic: 'Max Downforce / Low-Speed', 
        secondaryCharacteristic: null, 
        riskTier: 2, 
        wetSessionProbability: 0.25, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Esteban Ocon', 'Lewis Hamilton', 'Lewis Hamilton'] 
    },
    { 
        name: 'Circuit de Spa-Francorchamps', 
        description: "A legendary and iconic circuit, Spa-Francorchamps is a favourite among drivers and fans alike. It's a long, fast, and flowing track that winds its way through the Ardennes forest, featuring significant elevation changes and some of the most famous corners in motorsport, including Eau Rouge and Raidillon.", 
        laps: 44, 
        baseLapTime: 106, 
        downforceLevel: 3, 
        tyreStress: 5, 
        brakeWear: 3, 
        powerSensitivity: 5, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.63, 
        virtualSafetyCarProbability: 0.0, 
        pitLaneTimeLoss: 18.8, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'High-Speed Aero', 
        riskTier: 1, 
        wetSessionProbability: 0.70, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton', 'Charles Leclerc'] 
    },
    { 
        name: 'Circuit Zandvoort', 
        description: "A challenging, old-school circuit located in the sand dunes next to the North Sea, Zandvoort is known for its fast, flowing, and banked corners. The track has a rollercoaster-like feel with significant elevation changes.", 
        laps: 72, 
        baseLapTime: 75, 
        downforceLevel: 5, 
        tyreStress: 4, 
        brakeWear: 2, 
        powerSensitivity: 2, 
        overtakingDifficulty: 4, 
        drsEffectiveness: 3, 
        safetyCarProbability: 0.60, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 23.0, 
        primaryCharacteristic: 'Max Downforce / Med-Speed', 
        secondaryCharacteristic: 'Kerb Riding', 
        riskTier: 2, 
        wetSessionProbability: 0.40, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen'] 
    },
    { 
        name: 'Autodromo Nazionale Monza', 
        description: "The 'Temple of Speed,' Monza is the fastest circuit on the F1 calendar, with long straights and fast corners. It's a power-sensitive track where cars run with minimal downforce to maximize straight-line speed.", 
        laps: 53, 
        baseLapTime: 75, 
        downforceLevel: 1, 
        tyreStress: 2, 
        brakeWear: 4, 
        powerSensitivity: 5, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.70, 
        virtualSafetyCarProbability: 0.20, 
        pitLaneTimeLoss: 24.5, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: null, 
        riskTier: 1, 
        wetSessionProbability: 0.30, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Daniel Ricciardo', 'Pierre Gasly', 'Charles Leclerc'] 
    },
    { 
        name: 'Baku City Circuit', 
        description: "A unique street circuit that combines a long, incredibly fast main straight with a tight and twisting old town section. It's a track of two halves, demanding both high straight-line speed and excellent mechanical grip.", 
        laps: 51, 
        baseLapTime: 103, 
        downforceLevel: 2, 
        tyreStress: 2, 
        brakeWear: 5, 
        powerSensitivity: 5, 
        overtakingDifficulty: 1, 
        drsEffectiveness: 5, 
        safetyCarProbability: 1.00, 
        virtualSafetyCarProbability: 0.70, 
        pitLaneTimeLoss: 21.0, 
        primaryCharacteristic: 'Power & Traction', 
        secondaryCharacteristic: 'Low-Speed Technical', 
        riskTier: 3, 
        wetSessionProbability: 0.10, 
        pastWinners: ['Sergio Pérez', 'Max Verstappen', 'Sergio Pérez', 'Valtteri Bottas', 'Lewis Hamilton'] 
    },
    { 
        name: 'Marina Bay Street Circuit', 
        description: "A physically and mentally demanding street circuit that takes place at night under spectacular floodlights. The track is bumpy, and the hot and humid conditions make it one of the toughest races of the year for the drivers.", 
        laps: 62, 
        baseLapTime: 111, 
        downforceLevel: 5, 
        tyreStress: 3, 
        brakeWear: 4, 
        powerSensitivity: 2, 
        overtakingDifficulty: 5, 
        drsEffectiveness: 2, 
        safetyCarProbability: 1.00, 
        virtualSafetyCarProbability: 0.40, 
        pitLaneTimeLoss: 25.5, 
        primaryCharacteristic: 'Max Downforce / Med-Speed', 
        secondaryCharacteristic: 'Mechanical Grip', 
        riskTier: 2, 
        wetSessionProbability: 0.60, 
        pastWinners: ['Carlos Sainz Jr.', 'Sergio Pérez', 'Sebastian Vettel', 'Lewis Hamilton', 'Lewis Hamilton'] 
    },
    { 
        name: 'Circuit of the Americas', 
        description: "A modern, purpose-built circuit that has quickly become a favourite among drivers and fans. It features a great mix of corners inspired by other famous tracks, including a replica of Silverstone's Maggots-Becketts-Chapel complex.", 
        laps: 56, 
        baseLapTime: 96, 
        downforceLevel: 4, 
        tyreStress: 4, 
        brakeWear: 3, 
        powerSensitivity: 4, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.40, 
        virtualSafetyCarProbability: 0.30, 
        pitLaneTimeLoss: 20.0, 
        primaryCharacteristic: 'High-Speed Flow', 
        secondaryCharacteristic: 'Braking Stability', 
        riskTier: 2, 
        wetSessionProbability: 0.20, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Valtteri Bottas', 'Kimi Räikkönen'] 
    },
    { 
        name: 'Autódromo Hermanos Rodríguez', 
        description: "A high-altitude circuit that places unique demands on the cars and drivers. The thin air at over 2,200 meters above sea level means the cars run with maximum downforce, but the aerodynamic effect is reduced, leading to very high straight-line speeds.", 
        laps: 71, 
        baseLapTime: 80, 
        downforceLevel: 5, 
        tyreStress: 2, 
        brakeWear: 4, 
        powerSensitivity: 5, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.50, 
        virtualSafetyCarProbability: 0.40, 
        pitLaneTimeLoss: 21.5, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'Traction', 
        riskTier: 1, 
        wetSessionProbability: 0.25, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton', 'Max Verstappen'] 
    },
    { 
        name: 'Interlagos Circuit', 
        description: "A historic and challenging circuit with an anti-clockwise layout and significant elevation changes. It's a short, intense lap with a mix of fast, sweeping corners and a tight and twisty infield section.", 
        laps: 71, 
        baseLapTime: 73, 
        downforceLevel: 4, 
        tyreStress: 3, 
        brakeWear: 3, 
        powerSensitivity: 4, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.70, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 20.5, 
        primaryCharacteristic: 'High-Speed Flow', 
        secondaryCharacteristic: 'Low-Speed Technical', 
        riskTier: 2, 
        wetSessionProbability: 0.65, 
        pastWinners: ['Max Verstappen', 'George Russell', 'Lewis Hamilton', 'Max Verstappen', 'Lewis Hamilton'] 
    },
    { 
        name: 'Las Vegas Strip Circuit', 
        description: "A spectacular new street circuit that runs down the iconic Las Vegas Strip at night. The track is dominated by long straights and heavy braking zones, making it a power-sensitive circuit with plenty of overtaking opportunities.", 
        laps: 50, 
        baseLapTime: 94, 
        downforceLevel: 1, 
        tyreStress: 2, 
        brakeWear: 5, 
        powerSensitivity: 5, 
        overtakingDifficulty: 1, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.80, 
        virtualSafetyCarProbability: 0.50, 
        pitLaneTimeLoss: 19.0, 
        primaryCharacteristic: 'Power Sensitive', 
        secondaryCharacteristic: 'Braking Stability', 
        riskTier: 2, 
        wetSessionProbability: 0.05, 
        pastWinners: ['Max Verstappen'] 
    },
    { 
        name: 'Lusail International Circuit', 
        description: "A fast and flowing circuit with a long main straight and a series of medium and high-speed corners. It was originally built for MotoGP and has a smooth track surface. The race takes place at night under floodlights.", 
        laps: 57, 
        baseLapTime: 84, 
        downforceLevel: 4, 
        tyreStress: 5, 
        brakeWear: 2, 
        powerSensitivity: 4, 
        overtakingDifficulty: 3, 
        drsEffectiveness: 4, 
        safetyCarProbability: 0.20, 
        virtualSafetyCarProbability: 0.60, 
        pitLaneTimeLoss: 22.0, 
        primaryCharacteristic: 'High-Speed Aero', 
        secondaryCharacteristic: 'High-Speed Flow', 
        riskTier: 2, 
        wetSessionProbability: 0.05, 
        pastWinners: ['Max Verstappen', 'Lewis Hamilton'] 
    },
    { 
        name: 'Yas Marina Circuit', 
        description: "A state-of-the-art circuit that hosts the season finale. The track has been redesigned in recent years to improve the racing, with some of the slower chicanes removed to create faster, more flowing corners. The race starts in the daylight and finishes at night under floodlights.", 
        laps: 58, 
        baseLapTime: 88, 
        downforceLevel: 3, 
        tyreStress: 4, 
        brakeWear: 3, 
        powerSensitivity: 4, 
        overtakingDifficulty: 2, 
        drsEffectiveness: 5, 
        safetyCarProbability: 0.40, 
        virtualSafetyCarProbability: 0.30, 
        pitLaneTimeLoss: 20.0, 
        primaryCharacteristic: 'High-Speed Flow', 
        secondaryCharacteristic: 'Power & Traction', 
        riskTier: 1, 
        wetSessionProbability: 0.05, 
        pastWinners: ['Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Max Verstappen', 'Lewis Hamilton'] 
    },
];


export const SHORT_SEASON_TRACKS: Track[] = [
    'Bahrain International Circuit',
    'Jeddah Corniche Circuit',
    'Albert Park Circuit',
    'Autodromo Enzo e Dino Ferrari',
    'Circuit de Monaco',
    'Circuit Gilles Villeneuve',
    'Silverstone Circuit',
    'Circuit de Spa-Francorchamps',
    'Circuit Zandvoort',
    'Autodromo Nazionale Monza',
    'Marina Bay Street Circuit',
    'Suzuka International Racing Course',
    'Interlagos Circuit',
    'Yas Marina Circuit',
].map(name => FULL_SEASON_TRACKS.find(t => t.name === name)!);
